version: 2

sources:
    - name: bancamp
      # database: taxi-rides-ny-339813
      database: valued-watch-381913
      schema: bancamp_sales_ds
      tables:
        - name: bancamp_sales_table
      
models:
  - name: stg_bancamp 
    columns:
        - name: id
          description: Primary key for this table
      #Kiểm tra kiểu dữ liệu,.... khi run models
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn