
name: Deploy to Cloud 

on: 
  pull_request:
    branches:
     - main 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  run-flows:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "requriments*.txt"

      - name: Python dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install --upgrade --upgrade-strategy eager -r requriments.txt

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}}
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"

      - name: Run all flows
        id: run
        run: |
          python flows/gcs_to_bq.py

  deployment:
    name: Buid and apply deployment
    needs: run-flows
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:

      - name: Buid and apply deployment
        run: |
          prefect deployment build flows/etl_gcs_to_bq.py:etl_gcs_to_bq \
            -n "Main ETL" \
            -sb github/git-block \
            -t github \
            -q githubwq \
            -v $GITHUB_SHA \
            --apply
